services:
    ws.validator.rule.notblank:
        class: WS\JsFormValidatorBundle\Rules\NotBlank
        arguments: ['@translator', 'Symfony\Component\Validator\Constraints\NotBlank']
        tags:
            - { name: ws.validator.linker }
    
    ws.validator.rule.blank:
        class: WS\JsFormValidatorBundle\Rules\Blank
        arguments: ['@translator', 'Symfony\Component\Validator\Constraints\Blank']
        tags:
            - { name: ws.validator.linker }
    
    ws.validator.rule.notnull:
        class: WS\JsFormValidatorBundle\Rules\NotNull
        arguments: ['@translator', 'Symfony\Component\Validator\Constraints\NotNull']
        tags:
            - { name: ws.validator.linker }
    
    ws.validator.rule.null:
        class: WS\JsFormValidatorBundle\Rules\Null
        arguments: ['@translator', 'Symfony\Component\Validator\Constraints\Null']
        tags:
            - { name: ws.validator.linker }
    
    ws.validator.rule.true:
        class: WS\JsFormValidatorBundle\Rules\True
        arguments: ['@translator', 'Symfony\Component\Validator\Constraints\True']
        tags:
            - { name: ws.validator.linker }
    
    ws.validator.rule.false:
        class: WS\JsFormValidatorBundle\Rules\False
        arguments: ['@translator', 'Symfony\Component\Validator\Constraints\False']
        tags:
            - { name: ws.validator.linker }
    
    ws.validator.rule.type:
        class: WS\JsFormValidatorBundle\Rules\Type
        arguments: ['@translator', 'Symfony\Component\Validator\Constraints\Type']
        tags:
            - { name: ws.validator.linker }
    
    ws.validator.rule.email:
        class: WS\JsFormValidatorBundle\Rules\Email
        arguments: ['@translator', 'Symfony\Component\Validator\Constraints\Email']
        tags:
            - { name: ws.validator.linker }
    
    ws.validator.rule.length:
        class: WS\JsFormValidatorBundle\Rules\Length
        arguments: ['@translator', 'Symfony\Component\Validator\Constraints\Length']
        tags:
            - { name: ws.validator.linker }
    
    ws.validator.rule.choice:
        class: WS\JsFormValidatorBundle\Rules\Choice
        arguments: ['@translator', 'Symfony\Component\Validator\Constraints\Choice']
        tags:
            - { name: ws.validator.linker }

# Repeated fake constraint
    ws.validator.rule.repeated:
        class: WS\JsFormValidatorBundle\Rules\Repeated
        arguments: ['@translator', '\Repeated']
        calls:
            - [initValidator, ['@ws.validator_linker']]
        tags:
            - { name: ws.validator.linker }